name: Docs Quality Checks

on:
  pull_request:
    paths:
      - "**/*.md"

jobs:
  docs_quality:
    name: Lint Markdown & Check Links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

 
    
      # MARKDOWNLINT
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: markdownlint "**/*.md" --config .markdownlint.json

    
      # LYCHEE LINK CHECK
      - name: Install lychee
        uses: lycheeverse/lychee-action@v1.7.0
        with:
          args: --config lychee.toml ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
