name: Build Jobs documentation

on:
  push:
    paths:
      - "docs/jobs/**"
    branches:
      - main

jobs:
   build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: hub-docs
      package_name: jobs
      path_to_docs: hub-docs/docs/jobs/
      additional_args: --not_python_module
    secrets:
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
