name: JS Interfaces

on:
  push:
    paths:
      - "js/**"
      - "js/src/lib/interfaces/**"


jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - working-directory: js
        run: |
          npm ci
      - name: Check that code compiles
        working-directory: ./js/src/lib/interfaces
        run: |
          time npx tsc *.ts --lib es6,es2016,es2017,es2018,esnext --target es2018 --module commonjs --outDir dist
      - name: Run export-tasks script
        working-directory: js
        run: |
          npm run export-task
        # copy/paste this JSON output to any repo that might need it.
