name: Manual lint

# Could do on:pull_request with path on js/** to do it automatically
on:
  workflow_dispatch:

env:
  node_version: 18

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: js

jobs:
  version_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
      - run: npm install
      - run: git config --global user.name machineuser
      - run: git config --global user.email tech@huggingface.co
      - run: npm run format
      - run: git add .
      - run: git commit -m "ðŸš¨ Run prettier"
      - run: git push